import 'ionicons/dist/css/ionicons.css';
import './app.css';
import './form.css';
import './group.css';
import './icon.css';
import './item.css';
import './main.css';
import './menu.css';
import './panel.css';
